server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: readingIsGood
  security:
    filter:
      order: 5
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://postgres-db:5432/getir
    username: getir
    password: getir
    hikari:
      maximum-pool-size: 20
      minimum-idle: 4
  jpa:
    properties:
      org.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      hibernate.enable_lazy_load_no_trans: false
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
    open-in-view: false
    generate-ddl: true
  sql:
    init:
      mode: always
logging:
  file:
    path: c:\log\getir